Add more paths check for zsh and bash Refactor printing messages and warning

diff --git a/install b/install
--- a/install
+++ b/install
@@ -27,36 +27,55 @@ case "$filename" in
 esac
 
 INSTALL_DIR=$HOME/.sst/bin
-mkdir -p $INSTALL_DIR
+mkdir -p "$INSTALL_DIR"
 
 url="https://github.com/sst/ion/releases/latest/download/$filename"
 
 latest_version=$(curl -s https://api.github.com/repos/sst/ion/releases/latest | grep -oP '(?<="tag_name": ")[^"]+' | sed 's/^v//')
+
+print_message() {
+    local level=$1
+    local message=$2
+    local color=""
+    
+    case $level in
+        info) color="${GREEN}" ;;
+        warning) color="${YELLOW}" ;;
+        error) color="${RED}" ;;
+    esac
+    
+    echo -e "${color}${message}${NC}"
+}
+
+if [[ $? -ne 0 ]]; then
+    print_message error "Failed to fetch latest version"
+    exit 1
+fi
 
 check_version() {
     if command -v sst >/dev/null 2>&1; then
         installed_version=$(sst version)
         
         if [[ "$installed_version" != "$latest_version" ]]; then
-            read -p "${GREEN}Do you want to download the latest version? (y/n)${NC} " -n 1 -r
+            read -p "${GREEN}Update to latest version (${YELLOW}$latest_version${NC})? (y/n)${NC} " -n 1 -r
             echo
             if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                 exit 1
             fi
         else
-            echo -e "${GREEN}Already on latest version: ${YELLOW}$installed_version${NC}"
+            print_message info "Latest version $latest_version already installed"
             exit 0
         fi
     fi
 }
 
 download_and_install() {
-    echo -e "${GREEN}Downloading $filename version: ${YELLOW}$latest_version${NC} ${GREEN}...${NC}"
+    print_message info "Downloading $filename version: $latest_version ..."
     mkdir -p ssttmp && cd ssttmp
     curl -# -L $url | tar xz
     mv sst $INSTALL_DIR
     cd .. && rm -rf ssttmp
-    echo -e "${ORANGE}Successfully added SST to $INSTALL_DIR${NC}"
+    print_message info "Installed $filename to $INSTALL_DIR"
 }
 
 check_version
@@ -69,32 +88,61 @@ add_to_path() {
     if [[ -w $config_file ]]; then
         echo -e "\n# sst" >> "$config_file"
         echo "$command" >> "$config_file"
-        echo "Added $INSTALL_DIR to PATH in $config_file"
+        print_message info "Added $INSTALL_DIR to \$PATH in $config_file"
     else
-        echo -e "${YELLOW}Manually add the directory to $config_file (or similar):${NC}"
-        echo -e "${YELLOW}  $command ${NC}"
+        print_message warning "Manually add the directory to $config_file (or similar):"
+        print_message info "  $command"
     fi
 }
 
+XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
+
+declare -A shell_config_files=(
+    [fish]="$HOME/.config/fish/config.fish"
+    [zsh]="$HOME/.zshrc $HOME/.zshenv $XDG_CONFIG_HOME/zsh/.zshrc $XDG_CONFIG_HOME/zsh/.zshenv"
+    [bash]="$HOME/.bashrc $HOME/.bash_profile $XDG_CONFIG_HOME/bash/.bashrc $XDG_CONFIG_HOME/bash/.bash_profile"
+)
+
+current_shell=$(basename "$SHELL")
+
+config_files=${shell_config_files[$current_shell]}
+
+if [[ -z $config_files ]]; then
+    config_files="$HOME/.bashrc $HOME/.bash_profile $XDG_CONFIG_HOME/bash/.bashrc $XDG_CONFIG_HOME/bash/.bash_profile"
+fi
+
+config_file=""
+for file in $config_files; do
+    if [[ -f $file ]]; then
+        config_file=$file
+        break
+    fi
+done
+
+if [[ -z $config_file ]]; then
+    print_message error "No config file found for $current_shell. Checked files: ${config_files[@]}"
+    exit 1
+fi
+
 if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
-    case $(basename "$SHELL") in
+    case $current_shell in
         fish)
-            add_to_path "$HOME/.config/fish/config.fish" "fish_add_path $INSTALL_DIR"
+            add_to_path "$config_file" "fish_add_path $INSTALL_DIR"
         ;;
         zsh)
-            add_to_path "$HOME/.zshrc" "export PATH=$INSTALL_DIR:\$PATH"
+            add_to_path "$config_file" "export PATH=$INSTALL_DIR:\$PATH"
         ;;
         bash)
-            add_to_path "$HOME/.bashrc" "export PATH=$INSTALL_DIR:\$PATH"
+            add_to_path "$config_file" "export PATH=$INSTALL_DIR:\$PATH"
         ;;
         *)
-            echo -e "${ORANGE}Manually add the directory to ~/.bashrc (or similar):${NC}"
-            echo -e "${ORANGE}  export PATH=$INSTALL_DIR:\$PATH${NC}"
+            print_message warning "Manually add the directory to $config_file (or similar):"
+            print_message info "  export PATH=$INSTALL_DIR:\$PATH"
         ;;
     esac
 fi
 
 if [ -n "${GITHUB_ACTIONS-}" ] && [ "${GITHUB_ACTIONS}" == "true" ]; then
     echo "$INSTALL_DIR" >> $GITHUB_PATH
-    echo "${ORANGE}Added $INSTALL_DIR to PATH in GitHub Actions${NC}"
+    print_message info "Added $INSTALL_DIR to \$GITHUB_PATH"
 fi
